In [6]:
import pandas as pd

In [6]:
s = pd.Series([1, 3, 5, 6, 8])
print(s)
type(s)

0    1
1    3
2    5
3    6
4    8
dtype: int64

pandas.Series

In [8]:
s = pd.Series([1, 3, 5, 6, 8], index = ['a', 'b', 'c', 'd', 'e'])
print(s)
type(s)

a    1
b    3
c    5
d    6
e    8
dtype: int64

pandas.Series

In [11]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"jkl"]]

df = pd.DataFrame(data, columns=['col1', 'col2', 'col3'])
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

In [12]:
data = {"col1": [1, 2, 3, 4],
        "col2": [444, 555, 666, 444], 
        "col3": ["abc", "def", "ghi", "jkl"]}
df = pd.DataFrame(data)
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

In [10]:
df=pd.DataFrame([[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"jkl"]])
display(df)
columns = ['col1', 'col2', 'col3']
df.columns = columns
display(df)
df.index

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  jkl

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

RangeIndex(start=0, stop=4, step=1)

In [37]:
df.dtypes

col1    int64
col2    int64
col3      str
dtype: object

In [36]:
df['col3'].dtype

In [55]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"jkl"]]

data = {"col1": [1, 2, 3, 4],
        "col2": [444, 555, 666, 444], 
        "col3": ["abc", "def", "ghi", "jkl"]}
df = pd.DataFrame(data)
df
df['col3'].dtype

In [54]:
df['col1']= df['col1'].astype('float64')
df

   col1 col2 col3
0   1.0  444  abc
1   2.0  555  def
2   3.0  666  ghi
3   4.0  444  jkl

In [52]:
# cols = ['col1', 'col2', 'col3']

# df[cols] = df[cols].astype('category')

# df.dtypes

In [53]:
# exploratory data analysis (EDA) is an approach to analyzing data sets to summarize their main characteristics, often with visual methods. It is a critical step in the data science process, as it helps to understand the data, identify patterns, detect anomalies, and test hypotheses. EDA involves various techniques such as statistical summaries, data visualization, and correlation analysis to gain insights into the data before applying machine learning models or other analytical methods.
df.head
df.tail(1)

  col1 col2 col3
3    4  444  jkl

In [ ]:
df.describe()
"""
    describe() is a method in pandas that provides a summary of the statistical properties of a DataFrame or Series. It generates descriptive statistics that summarize the central tendency, dispersion, and shape of the dataset's distribution, excluding NaN values. The output includes metrics such as count, mean, standard deviation, minimum, maximum, and various percentiles (25th, 50th, and 75th). This method is useful for quickly understanding the characteristics of numerical data in a dataset.


"""

           col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [44]:
df.describe(include ='category')

        col1  col2 col3
count      4     4    4
unique     4     3    4
top        1   444  abc
freq       1     2    1

In [45]:
df['col1'].unique()

[1, 2, 3, 4]
Categories (4, int64): [1, 2, 3, 4]

In [46]:
df['col2'].nunique()

3

In [56]:
df['col2'].sum()

np.int64(2109)

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [ ]:
df['col2'].value_counts() #the repeated values in the column and their counts

col2
444    2
555    1
666    1
Name: count, dtype: int64