### Preprocessing Steps:-
1. Business understand
2. Data understanding
3. Drop non-intersing features
4. check dtypes
5. handle dtypes
6. check nulls
7. handle nulls
8. check outliers
9. handle outliers
10. check duplications
11. handle duplications
12. Data visualization
    - Dashboards
    - Distributions
13. Data spliting
14. Normalization
15. Encoding

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Titanic.csv')
type(df)

pandas.DataFrame

In [5]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
print(df.head())
print(df.tail())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

# 3. Drop non-intersting features

In [7]:
# # we don't need passengerId, name, and ticket. So we will drop them
# df.drop(['PassengerId', 'Name', 'Ticket'], axis = 1, inplace = True)

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
# converting df.drop() to a function
def drop_cols(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    return df.drop(columns=cols)

In [56]:
df = pd.read_csv("Titanic.csv")

cols = ['PassengerId', 'Name', 'Ticket']
df = drop_cols(df, cols)
df.columns
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [53]:
# #rereading
# df = pd.read_csv("Titanic.csv")

In [59]:
# we can even make a config.py file and import form it, if every time the file has these columns
df = pd.read_csv("Titanic.csv")
from config import COLS_DROP
from preprocessing import drop_cols
df = drop_cols(df, COLS_DROP) # to drop the columns in COLS_DROP from the df end of recent edits

In [60]:
dtypes = df.dtypes
print(dtypes)

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

# 4. Check Dtypes

In [64]:
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtypes": dtypes, "nunique": nunique}).T #nunique is the number of unique values in each column. It helps us to understand the data better and to decide which columns to drop or keep.
# from this we can conclude that survived, pclass, sibsp, parch, embarked, and sex, their dtypes need to be changed
# 2( or 1), 3 (class 1, 2, 3), 2(male, female) they categorical variables. We can convert them to categorical type using astype() method.

        Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
dtypes     int64  int64  str  float64  int64  int64  float64   str      str
nunique        2      3    2       88      7      7      248   147        3

In [62]:
df.info() #714, 204, 889 are null values in the columns age, cabin, and embarked respectively. We can drop cabin because it has too many null values. For age and embarked we can fill them with mean and mode respectively.

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    str
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    str
 8   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(3)
memory usage: 62.8 KB

# 5. Handle dtypes

In [ ]:
# cat for categorical
cat_cols = ['Survived', "Pclass", "Sex", "SibSp", "Parch", "Embarked"]
df[cat_cols] = df[cat_cols].astype("category")

In [72]:
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtypes": dtypes, "nunique": nunique}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,str,category
nunique,2,3,2,88,7,7,248,147,3

In [67]:
def get_type_info(df):
    return pd.DataFrame({"dtypes": df.dtypes, "nunique": df.nunique()}).T

In [73]:
get_type_info(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,str,category
nunique,2,3,2,88,7,7,248,147,3

In [19]:
df.select_dtypes("category") # to select only the categorical columns from the df. This is useful when we want to apply some operations only on categorical columns.

    Survived Pclass     Sex SibSp Parch Embarked
0          0      3    male     1     0        S
1          1      1  female     1     0        C
2          1      3  female     0     0        S
3          1      1  female     1     0        S
4          0      3    male     0     0        S
..       ...    ...     ...   ...   ...      ...
886        0      2    male     0     0        S
887        1      1  female     0     0        S
888        0      3  female     1     2        S
889        1      1    male     0     0        C
890        0      3    male     0     0        Q

[891 rows x 6 columns]

# 6. Check Nulls
# 7. Handle Nulls

In [74]:
df.isnull()

     Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

In [90]:
null = df.isnull().sum()
print(null)
ratio = (null / 891) * 100
ratio

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

Survived    0.0
Pclass      0.0
Sex         0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
Embarked    0.0
dtype: float64

In [21]:
# for example you're in a company and want to decide from the three cols: age, cabine, and embarked
# most of values exist (about 30%) use the mode in case of a categorical data
# otherwise, if most of the data is missing, drop the column
# embarked has only 2 rows that has missing values, you can use the mode, or drop the two rows
# you can even link a column by another column and  produce a prdiction according to the other linked columns

In [ ]:
df = df.dropna(subset=['Embarked']) #dropna to drop the rows that have null values in the Embarked column. This is because the number of rows with null values in the Embarked column is very small (only 2 rows), so dropping them will not affect the dataset significantly.

In [78]:
df = df.drop("Cabin", axis = 1)

In [91]:
df.describe() # to get the statistical summary of the numerical columns in the df. It helps us to understand the data better and to decide which columns to drop or keep.

              Age        Fare
count  889.000000  889.000000
mean    29.315152   32.096681
std     12.984932   49.697504
min      0.420000    0.000000
25%     22.000000    7.895800
50%     28.000000   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200

In [92]:
df.describe()
median = df['Age'].median()
print(median)

28.0

In [93]:
df['Age'] = df['Age'].fillna(median, inplace= True) # fill the null values in the Age column with the median value. This is a common approach when dealing with missing data in numerical columns.

C:\Users\bavly\AppData\Local\Temp\ipykernel_2428\1254029175.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'] = df['Age'].fillna(median, inplace= True) # fill the null values in the Age column with the median value. This is a common approach when dealing with missing data in numerical columns.

In [94]:
null = df.isnull().sum()
ratio = (null / 891) * 100
pd.DataFrame({"null": null, "ratio": ratio})

          null  ratio
Survived     0    0.0
Pclass       0    0.0
Sex          0    0.0
Age          0    0.0
SibSp        0    0.0
Parch        0    0.0
Fare         0    0.0
Embarked     0    0.0

# 8. Check Outliers
# 9. Handle Outliers

IQR for handling outliers
it draws the safe zone of the data

In [95]:
num_col = df.select_dtypes("number").columns
num_col

Index(['Age', 'Fare'], dtype='str')

In [100]:
num_col = df.select_dtypes("number").columns
num_col
for col in num_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    print(Q1, Q3)
    IQR = Q3 - Q1
    print("IQR:", IQR)
    lower_fence = Q1 - 1.5 * IQR
    upper_fence = Q3 + 1.5 * IQR
    print("Lower fence:", lower_fence, "Upper fence:", upper_fence)

22.0 35.0
IQR: 13.0
Lower fence: 2.5 Upper fence: 54.5
7.8958 31.0
IQR: 23.1042
Lower fence: -26.7605 Upper fence: 65.6563

In [99]:
df.describe()

              Age        Fare
count  889.000000  889.000000
mean    29.315152   32.096681
std     12.984932   49.697504
min      0.420000    0.000000
25%     22.000000    7.895800
50%     28.000000   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200